kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-read-only
rules:
- apiGroups: ["core/v1"]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-read-only
subjects:
- kind: User
  name: cxtenberge5@gmail.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: node-read-only
  apiGroup: rbac.authorization.k8s.io
